from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 600)
        MainWindow.setStyleSheet("background-color: rgb(188, 234, 234);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.row = QtWidgets.QLabel(self.centralwidget)
        self.row.setGeometry(QtCore.QRect(150, 240, 321, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.row.setFont(font)
        self.row.setObjectName("row")
        self.column = QtWidgets.QLabel(self.centralwidget)
        self.column.setGeometry(QtCore.QRect(130, 320, 341, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.column.setFont(font)
        self.column.setObjectName("column")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(500, 240, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(500, 320, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.tool = QtWidgets.QLabel(self.centralwidget)
        self.tool.setGeometry(QtCore.QRect(290, 140, 191, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.tool.setFont(font)
        self.tool.setObjectName("tool")
        self.return_button = QtWidgets.QPushButton(self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(330, 440, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.return_button.setFont(font)
        self.return_button.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(217, 226, 255);")
        self.return_button.setObjectName("return_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.row.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00557f;\">Изменить количество строк </span></p></body></html>"))
        self.column.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00557f;\">Изменить количество столбцов</span></p></body></html>"))
        self.tool.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#00557f;\">Настройки</span></p></body></html>"))
        self.return_button.setText(_translate("MainWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
